### ISSUE TITLE
Fix not priority

### ISSUE THREAD

**Issue by bitbart** [AngeloFerrando/Solvent#27]
Not should have priority over || and &&.

Consider the contract `regression/not-priority.sol`: 
```
contract NotPriority {
    function pay() {
      msg.sender!1
    }
}
```
and consider the following property: 
```
property p1_live {
    Forall xa
    [
      not false || true
        ->
      Exists tx [1, xa]
      [
        ((app_tx_st.balance[xa] == st.balance[xa] + 1000))
      ]
    ]
}
```
The correct parenthesization of `not false || true` should be `(not false) || true`, which is true. Therefore, the property should be false since the contract could not have enough balance to pay `xa`.

Instead, the tool returns:
```
PROPERTY: out/smt2/p1_live
LIVE
```
This is only possible is `not false || true` is paranthesized as ``not (false || true) = false``: in this way, the property is trivially true since the antecedent of the implication is false.

Note that by manually parenthesizing the expression, the verifier's outputs is correct: 
```
property p2_live {
    Forall xa
    [
      (not false) || true
        ->
      Exists tx [1, xa]
      [
        ((app_tx_st.balance[xa] == st.balance[xa] + 1000))
      ]
    ]
}
```
```
PROPERTY: out/smt2/p2_live
NOT LIVE (COUNTEREXAMPLE FOUND AND STORED IN out/smt2/p2_live/counterexample.txt)
```

**Comment by AngeloFerrando** [comment]
Commit 41f357d fix this issue
