### ISSUE TITLE
Use "immutable" instead of "const"

### ISSUE THREAD

**Issue by bitbart** [AngeloFerrando/Solvent#42]
Use the Solidity syntax for constants. For instance, use:
```
int immutable end_donate
```
instead of:
```
const int end_donate
```
Extend the type checker according for coherence with Solidity:

https://soliditylang.org/blog/2020/05/13/immutable-keyword/

**Comment by AngeloFerrando** [comment]
Commit 3f8eb3f solves this issue.

**Comment by bitbart** [comment]
The correct syntax should be:
```
type immutable varname
```
For example:
```
int immutable end_donate
```
while the fix supports a wrong syntax (i.e., the Solidity compiler gives an error):
```
immutable int  end_donate
```

**Comment by AngeloFerrando** [comment]
Commit 18e5fa1 solves this issue.
