### ISSUE TITLE
Confusion between sender and msg.sender

### ISSUE THREAD

**Issue by bitbart** [AngeloFerrando/Solvent#57]
The tool currently interprets `sender` as `msg.sender`, causing some confusion. 

For instance, consider the contract regression/sender.sol:
```
contract Sender {
  address sender

  function receive() payable { skip }

  // error: it should be msg.sender
  function pay() { sender!balance }
}
```
Here, the variable `sender` is assumed equal to `msg.sender`, and so the following property is classified as live:
```
property pay_nonlive {
    Forall xa
    [
      st.balance>0
        ->
      Exists tx [1, xa]
      [
        (app_tx_st.balance[xa] > st.balance[xa])
      ]
    ]
}
```

**Comment by AngeloFerrando** [comment]
Commit 76c6dea solves this issue.
