### ISSUE TITLE
Towards Solidity syntax: external visibility modifier

### ISSUE THREAD

**Issue by bitbart** [AngeloFerrando/Solvent#63]
Add `external` visibility modifier for all functions (but the constructor).

For example, in the Crowdfund use case:
```
function donate() payable external {
        require (block.number <= end_donate);
        donors[msg.sender] = donors[msg.sender] + msg.value;
        if (address(this).balance >= target) 
            target_reached = true;
    }

    function wdOwner() external {
        require (target_reached && block.number > end_donate);
        (bool succ,) = owner.call{value: address(this).balance}("");
        require(succ);
    }
```
External functions can be called by external transactions (namely, by EOAs or other contracts).

Note that `external` is [different](https://mdjamilkashemporosh.medium.com/modifiers-in-solidity-public-private-internal-and-external-764d0aae9c) from `public`, in that `external` methods cannot be called by other methods of the same contract. 

The constructor has no visibility modifiers.

**Comment by AngeloFerrando** [comment]
Commit ba40523 solves this issue.
